version: "3"
services:
    mssql1:
      build: ./mssql1
      volumes:
        - mydata:/var/opt/backups
        - sharedpath:/sharedpath
      environment:
          SA_PASSWORD: "Password1234!"
          ACCEPT_EULA: "Y"
          MSSQL_BACKUP_DIR: /var/opt/backups
          TZ: Europe/London
          MSSQL_AGENT_ENABLED: "True"
      ports:
        - "2500:1433"
      container_name: mssql1
      hostname: mssql1
    mssql2:
      build: ./mssql2
      volumes:
        - mydata:/var/opt/backups
        - sharedpath:/sharedpath
      environment:
          SA_PASSWORD: "Password1234!"
          ACCEPT_EULA: "Y"
          MSSQL_BACKUP_DIR: /var/opt/backups
          MSSQL_AGENT_ENABLED: "True"
          TZ: Europe/London
      ports:
          - "2600:1433"
      container_name: mssql2
      hostname: mssql2

volumes:
  mydata:
  sharedpath:
