version: "3"
services:
    dbatools1:
      image: dbatools/sqlinstance
      volumes:
        - shared:/shared

      ports:
        - "2500:1433"
      container_name: dbatools1
      hostname: dbatools1
      
    dbatools2:
      image: dbatools/sqlinstance2
      volumes:
        - shared:/shared

      ports:
        - "2600:1433"
      container_name: dbatools2
      hostname: dbatools2

volumes:
  mydata:
  shared: